package com.oneapm.activiti.test.domain;

public class TblC {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_c.c1
     *
     * @mbggenerated
     */
    private Integer c1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_c.c2
     *
     * @mbggenerated
     */
    private String c2;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_c.c1
     *
     * @return the value of tbl_c.c1
     *
     * @mbggenerated
     */
    public Integer getC1() {
        return c1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_c.c1
     *
     * @param c1 the value for tbl_c.c1
     *
     * @mbggenerated
     */
    public void setC1(Integer c1) {
        this.c1 = c1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_c.c2
     *
     * @return the value of tbl_c.c2
     *
     * @mbggenerated
     */
    public String getC2() {
        return c2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_c.c2
     *
     * @param c2 the value for tbl_c.c2
     *
     * @mbggenerated
     */
    public void setC2(String c2) {
        this.c2 = c2 == null ? null : c2.trim();
    }
}