package com.oneapm.activiti.test.mapper;

import com.oneapm.activiti.test.domain.TblC;
import com.oneapm.activiti.test.domain.TblCCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TblCMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_c
     *
     * @mbggenerated
     */
    int countByExample(TblCCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_c
     *
     * @mbggenerated
     */
    int deleteByExample(TblCCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_c
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer c1);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_c
     *
     * @mbggenerated
     */
    int insert(TblC record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_c
     *
     * @mbggenerated
     */
    int insertSelective(TblC record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_c
     *
     * @mbggenerated
     */
    List<TblC> selectByExample(TblCCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_c
     *
     * @mbggenerated
     */
    TblC selectByPrimaryKey(Integer c1);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_c
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TblC record, @Param("example") TblCCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_c
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TblC record, @Param("example") TblCCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_c
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TblC record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_c
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TblC record);
}